### ISSUE TITLE
POC Authentication with firebase admin

### ISSUE THREAD

**Issue by rmuti56** [peuan/travelmate-api#1]
## Tasks
- [ ] Guide on connecting the front-end with Firebase API on the back-end
- [ ] Explanation of the required endpoint for Firebase integration
- [ ] Instructions on storing user information in our database, noting that Firebase only stores the `userId`
